Ma'lumotlarni t≈çldirish

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

Y√µq NaN qiymatlarini √µrnini t√µldirish

In [ ]:
# barcha y≈çq qiymatlar √µrniga standard 0 qiymat berish
df.fillna(0) # fillna t≈çldirish deb nomlanadi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,0.0,21.0,13495.0
1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,0.0,0.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,0.0,171.7,0,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,0.0,ohc,four,100.0,0.0,9995.0
87,volvo,sedan,104.3,188.8,0,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,0.0,23.0,13415.0

In [ ]:
# Ma'lum bir ustunlar uchun qiymat berish
# horsepower ustun uchun 100 qiymat, wheel-base ustun uchun 90 qiymat
df.fillna({'horsepower':100, 'wheel-base':90})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,100.0,21.0,13495.0
1,alfa-romero,convertible,90.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,100.0,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,90.0,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,100.0,23.0,13415.0

In [ ]:
# √ïrta qiymatlarni olish
np.mean(df['wheel-base']) # wheel-base ustuni uchun √µrta qiymatni hisoblash

99.2195652173913

In [ ]:
# bu erda horsepower va wheel-base ustunlarida y√µq qiymatlar uchun √µrta qiymatni kiritish
df.fillna({'horsepower':np.mean(df['horsepower']), 'wheel-base':np.mean(df['wheel-base'])})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.8,dohc,four,108.266667,21.0,13495.0
1,alfa-romero,convertible,99.219565,168.8,dohc,four,111.000000,21.0,16500.0
2,alfa-romero,hatchback,94.500000,171.2,ohcv,six,154.000000,NaN,16500.0
3,audi,sedan,99.800000,176.6,ohc,four,102.000000,24.0,13950.0
4,audi,sedan,99.400000,176.6,ohc,five,108.266667,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.7,ohc,four,85.000000,27.0,7975.0
82,volkswagen,sedan,99.219565,171.7,NaN,four,52.000000,37.0,7995.0
86,volkswagen,sedan,97.300000,NaN,ohc,four,100.000000,NaN,9995.0
87,volvo,sedan,104.300000,188.8,NaN,four,114.000000,23.0,12940.0
88,volvo,wagon,104.300000,188.8,ohc,four,108.266667,23.0,13415.0

Mavjud b√µlmagan NaN qiymatlarini √µrnini t√µldirishni yana bir usuli

In [ ]:
# Mavjud b√µlmagan qiymatlarni √µzidan avvalgi qiymat bilan t√µldirib ketish
# ffill - oldinga qarab t√µldirib ketish
df.fillna(method='ffill')

<ipython-input-12-8c65e1e63883>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [ ]:
# Mavjud b√µlmagan qiymatlarni √µzidan keyingi qiymat bilan t√µldirib ketish
# bfill - keyingi qarab t√µldirib ketish
df.fillna(method='bfill')

<ipython-input-13-463358a313b4>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
# Kompaniyasi b√µyicha ajratish
df[df.company=='toyota']

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,NaN,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
df[df.company=='toyota'].fillna(method='bfill')

<ipython-input-15-29c7b327e05f>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='toyota'].fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [ ]:
# hatchback masinalari uchun √µrtacha qiymatni berish
dfh = df[df['body-style']=='hatchback']

In [ ]:
import pandas as pd

# –ü—Ä–∏–º–µ–Ω—è–µ–º fillna —Ç–æ–ª—å–∫–æ –∫ —á–∏—Å–ª–æ–≤—ã–º —Å—Ç–æ–ª–±—Ü–∞–º
dfh_numeric = dfh.select_dtypes(include=[int, float])

# –ó–∞–ø–æ–ª–Ω—è–µ–º –ø—Ä–æ–ø—É—â–µ–Ω–Ω—ã–µ –∑–Ω–∞—á–µ–Ω–∏—è —Å—Ä–µ–¥–Ω–∏–º–∏ —Ç–æ–ª—å–∫–æ –≤ —á–∏—Å–ª–æ–≤—ã—Ö —Å—Ç–æ–ª–±—Ü–∞—Ö
dfh[dfh_numeric.columns] = dfh_numeric.fillna(dfh_numeric.mean())
dfh

<ipython-input-21-d8ff3bbd7a78>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfh[dfh_numeric.columns] = dfh_numeric.fillna(dfh_numeric.mean())

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
2,alfa-romero,hatchback,94.500000,171.200,ohcv,six,154.0,32.727273,16500.000000
16,chevrolet,hatchback,88.400000,141.100,l,three,78.9,47.000000,5151.000000
17,chevrolet,hatchback,94.500000,155.900,ohc,four,70.0,38.000000,6295.000000
19,dodge,hatchback,93.700000,157.300,ohc,four,68.0,31.000000,6377.000000
20,dodge,hatchback,93.700000,159.325,ohc,four,68.0,32.727273,6229.000000
36,mazda,hatchback,93.100000,159.100,NaN,four,78.9,32.727273,5195.000000
37,mazda,hatchback,93.100000,159.100,ohc,four,68.0,31.000000,6095.000000
38,mazda,hatchback,93.100000,159.100,ohc,four,68.0,31.000000,6795.000000
39,mazda,hatchback,93.809091,159.325,NaN,two,101.0,17.000000,11845.000000
49,mitsubishi,hatchback,93.809091,157.300,ohc,four,78.9,37.000000,5389.000000
50,mitsubishi,hatchback,93.700000,159.325,NaN,four,68.0,31.000000,6189.000000
63,porsche,hatchback,98.400000,175.700,dohcv,eight,78.9,32.727273,7159.571429
66,toyota,hatchback,93.809091,158.700,ohc,four,62.0,35.000000,5348.000000
67,toyota,hatchback,95.700000,158.700,NaN,four,78.9,31.000000,6338.000000
68,toyota,hatchback,93.809091,158.700,ohc,four,62.0,31.000000,6488.000000