In [ ]:
import pandas as pd
import numpy as np

.map() qiymatlarni moslashtirish(almashtirish)

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

Ustunlarni qiymatlariga õzgartirish kiritish

.map()
.apply()

In [ ]:
# DataFrame da num-of-cylinders ustunida qiymatlar text kõtinishida yozilgan
# shu qiymatlarni son kõrinishiga õzgartiramiz
# qiymatlarini oldin kõrib chiqamiz
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [ ]:
# Oldin lugat yaratib olamiz va har biriga sondagi qiymatini berib chiqamiz
dict = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}
df['cylinders'] = df['num-of-cylinders'].map(dict) # yangi 'cylindes' ustun tushdi .map() yordamida
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4

In [ ]:
# price - narh ustunini chiqaramiz
df['price']

index
0     13495.0
1     16500.0
2     16500.0
3     13950.0
4     17450.0
       ...
81     7975.0
82     7995.0
86     9995.0
87    12940.0
88    13415.0
Name: price, Length: 61, dtype: float64

In [ ]:
# price ustunida narhlar dollarda yozilgan
# shu dollarni sõm kõrinishga õtkizamiz
# masalan kurs hozirda 10720 tahminan
kurs = 10720
df['price'].map(lambda x: x*kurs) # lambda bu erda bir martalik funksiya

index
0     144666400.0
1     176880000.0
2     176880000.0
3     149544000.0
4     187064000.0
         ...
81     85492000.0
82     85706400.0
86    107146400.0
87    138716800.0
88    143808800.0
Name: price, Length: 61, dtype: float64

In [ ]:
# bu õzgarishlarni 'price_uz' ustuniga saqlab olamiz
kurs = 10720
df['price_uz'] = df['price'].map(lambda x: x*kurs)
df # jadvalni ohida yangi ustun paydo bõldi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,143808800.0

.replace() va .rename() - qiymatlarni almashtirish

In [ ]:
# qiymatlar õrniga qõyib yozish
df.replace('four', 4) # ustunlardagi four qiymatlar õrniga 4 raqam yoziladi

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [ ]:
# yana bir misol
df.replace('six', 6)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,143808800.0

In [ ]:
# birdaniga bir nechta qiymatlarni õzgartirish
df.replace(dict)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,6,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,5,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [ ]:
# Yangi DataFrame yuklab olamiz
df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', index_col='country')

In [ ]:
df2.head()

         rank     density   densityMi    pop2021   area
country
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2
Burundi    28    440.3044   1140.3884  12255.433  27834
Macau       1  21946.4667  56841.3487    658.394     30
Monaco      2  19755.5000  51166.7450     39.511      2

In [ ]:
# rename() metodi ustunlarni, qatorlarni nomini õzgartiradi
df2.rename(index=str.upper) # index teks bõlgani uchun str ni qõshib yoziladi
# natija index katta harfga õzgaradi

                  rank     density   densityMi    pop2021     area
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
# ustunlarni katta harfga õzgartirish
df2.rename(columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
# index va ustunlarni nomlari katta harflar bilan yozish
df2.rename(index=str.upper, columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [ ]:
# ustunlarni ichidan tanlab nomini õzgartirish
# masalan pop2021 ustun nomini population ga õzgartirish
df2.rename(columns={"pop2021":"population"})
# õzgarishlarni saqlab qõyish uchun ohirida inplace=True komandasini beramiz

                  rank     density   densityMi  population     area
country
Macau                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
Burundi             28    440.3044   1140.3884   12255.433    27834
Macau                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
...                ...         ...         ...         ...      ...
Namibia            228      3.1338      8.1166    2587.344   825615
Western Sahara     229      2.3003      5.9577     611.875   266000
Mongolia           230      2.1286      5.5129    3329.289  1564110
Falkland Islands   231      0.2902      0.7517       3.533    12173
Greenland          232      0.0263      0.0680      56.877  2166086

[247 rows x 5 columns]

In [ ]:
# index larni õzgartirish
df2.rename(index={"Macau":"Makao"})

                  rank     density   densityMi    pop2021     area
country
Makao                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Makao                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]